import random
import math
x=random.uniform(2.0,8.00)
print("using trunc for rounding:",math.trunc(x))
print("using ceil for rounding:",math.ceil(x))
print("using floor for rounding:",math.floor(x))
#round function is not a part of math libraries
print("using round for rounding:",round(x,2))
print("rounding -2.8",math.ceil(-2.8))
print("rounding -0.5",math.ceil(-0.5))
print("rounding 0.2",math.ceil(0.2))
print("rounding 1.5",math.ceil(1.5))
print("rounding 2.9",math.ceil(2.9))
print()
print("rounding -2.8",math.trunc(-2.8))
print("rounding -0.5",math.trunc(-0.5))
print("rounding 0.2",math.trunc(0.2))
print("rounding 1.5",math.trunc(1.5))
print("rounding 2.9",math.trunc(2.9))
print()
print("rounding -2.8",math.floor(-2.8))
print("rounding -0.5",math.floor(-0.5))
print("rounding 0.2",math.floor(0.2))
print("rounding 1.5",math.floor(1.5))
print("rounding 2.9",math.floor(2.9))
print()
print("rounding -2.8",round(-2.8,1))
print("rounding -0.5",round(-0.5,1))
print("rounding 0.2",round(0.2,1))
print("rounding 1.5",round(1.5,1))
print("rounding 2.9",round(2.9,1))