str=input("please enter the no.of lines you want:")
msg="kese ho"
print(str[0:])
print(str[:8])
#print(str[9])->error
print(str[0:8])
print(str[-8:])
print(str[:-1])
print(str[::-1])
print('_'*20)
print(len(str))
print(max(str))
print(min('hello ji'))
print(str.find('llo'))
print(str.replace('o','k'))
print(str.split(" "))
print(str.partition('l'))
print(str.startswith('0'))
print(complex("11"))